[google_cloud]
project = "project-name"
bucket = "bucket-name"
images_bucket = "images-bucket-name"

[vertex_ai_machine_config]
machine_type = "n1-standard-4" # The type of machine to use. Refer to: https://cloud.google.com/vertex-ai/docs/training/configure-compute#machine-types
accelerator_type = "NVIDIA_TESLA_T4" # The type of accelerator to use. Refer to: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/MachineSpec#acceleratortype
accelerator_count = 1 # number of accelerators

[label_studio]
project_url = "project-url"
token = "token"

[training]
use_kfold = true
number_of_folds = 2
epochs = 1
model = "yolov8n.pt"
image_size = "960, 540"

[mlflow]
tracking_uri = "http://127.0.0.1:5000"
experiment_name = "experiment-name"
run = "run-name"
user = "user"
password = "password"